export type ErrorType =
  | "technical"
  | "autoresubmittion"
  | "codesuggestion"
  | "writeoff"
  | "paymentmatch"
  | "unmatchpayment"
  | "medicalnecessity"
  | "noteligible"
  | "outofnetwork"
  | "panotrequire"
  | "paapproved"
  | "panotapproved"
  | "paappeal"
  | "underpayment"
  | "overpayment"
  | "partialpayment"
  | "costtopatient"
  | "pandingapproval"
  | "overautomation"
  | "partialapproval";

export type ErrorCode =
  | "T500"
  | "AI-RESUB-001"
  | "CMS-110"
  | "MN-REQ-001"
  | "WR-105"
  | "CC-001"
  | "MN-002"
  | "APL-003"
  | "test"
| "notcovered"
  | "OA-ERR-001";
